## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Emprove"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A local volunteer platform"
  logo = "/public/images/bluebonnet.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/Benjamin00/emprove"
  twitter = "https://twitter.com/"
  email = ""
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"
  telegram = "https://telegram.org"